### ISSUE TITLE
Only the last entry in an Electron ASAR Unpack array is shipped

### ISSUE THREAD

**Issue by trulysinclair** [hydraulic-software/conveyor#112]
**Describe the bug**
When specifying multiple files or globs to be unpacked, only the last entry of the array is added to the final build. However, in dev such as using "conveyor run" it appears to work as expected.

**To Reproduce**
1. Specify multiple entries to unpack
2. Package the application "conveyor make app"
3. Open the output directory under "resources/app.asar.unpacked/"
4. See only the last entry such as either "node_modules" or "product.json"

**Expected behavior**
All entries should be available under the unpacked directory, in my case, a product.json, pwd.db, Prisma ".node" files, and the Prisma Scheme engine ".exe" file.

**Screenshots**
Here's the last entry commented out which shows the node files: 
![image](https://github.com/hydraulic-software/conveyor/assets/11479772/b06a59da-daae-4257-9782-dbdd9cfd2bda)

Here's the last entry uncommented which shows only the pwd.db file:
![image](https://github.com/hydraulic-software/conveyor/assets/11479772/4b9f436b-eb20-4d8e-9d91-318c9d7ba140)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: N/A
 - Version Conveyor 14.2
 - Npm: 10.8
 - Yarn: 14.1 (node-compat)

**Additional context**

I've also tried turning prune on and off which didn't change anything. It should be noted that individual additions using `electron.asar.unpack += "..."` does not produce the same output as an explicit array declaration. Instead, only the last array is produced in the JSON output.

![image](https://github.com/hydraulic-software/conveyor/assets/11479772/11869df1-dae6-4bfb-b04a-d4a5092b4fe4)

However, explicit definition does of course work.

```hocon
electron.asar.unpack = [
    "product.json"
    "**/*.node"
    "**/*.exe"
    "pwd.db"
  ]
```

**Comment by mikehearn** [comment]
This should be fixed in 14.3
