### ISSUE TITLE
The version in generated appcast-*.rss does not match the defined app.version

### ISSUE THREAD

**Issue by guiyanakuang** [hydraulic-software/conveyor#118]
**Describe the bug**
When running `gradlew -q printConveyorConfig`, the output is:
```
.....
app.version = 1.0.0
.....
```
However, the generated appcast-amd64.rss file
```xml
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
    <channel>
        <title>Changelog</title>
        <link>http://localhost:3000/appcast-amd64.rss</link>
        <description>Most recent changes with links to updates.</description>
        <language>en</language>
        <item>
            <title>Version 1.0.0.0</title>
            <link>http://localhost:3000/</link>
            <sparkle:version>1.0.0.0</sparkle:version>
            <description>
                <![CDATA[ New release: version 1.0.0.0 ]]>
            </description>
            ........
        </item>
    </channel>
</rss>
```
The version in the appcast-amd64.rss is 1.0.0.0, which does not match the defined app.version of 1.0.0.

**Additional context**
 - OS: MacOS 14.5 Intel
 - Version 14.3

**Comment by mikehearn** [comment]
That's intentional. The last number comes from the `app.revision` key, which is intended to be used if you change the packaging configuration but not the underlying code. The idea is that the revision number can be hidden in the app UI. same thing is done on Windows. It's useful when packaging other people's software for example, as the 4th digit normally isn't used.

**Comment by guiyanakuang** [comment]
However, Sparkle will use this combined version number and display it in the upgrade UI, which I am concerned might confuse users. Users generally do not care about the revision number.

**Comment by mikehearn** [comment]
The fix for this should go out in the next minor release, thanks for the suggestion!
