### ISSUE TITLE
Better error message if YubiKey is not connected

### ISSUE THREAD

**Issue by Christilut** [hydraulic-software/conveyor#129]
**Describe the bug**
If my yubikey is not connected I get the following error during build:

```
❌ Internal error: Provider: Initialization failed
Provider: slotListIndex is 0 but token only has 0 slots
The application has crashed. Use --show-log for details.
To submit a crash report, please type 'y' and press enter.
```

**Expected behavior**
A more clear error indicating that the hardware device is not connected

**Screenshots**

**Desktop (please complete the following information):**
Windows

**Comment by mikehearn** [comment]
Thanks. We got a similar complaint recently and a fix is already queued up for the next release.
