### ISSUE TITLE
zulu on macosx results in DirectoryNotEmptyException

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#13]
using `required("/stdlib/jdk/18.0.1+10/azul.conf")` results in a `DirectoryNotEmptyException` when building the mac-app, but `required("/stdlib/jdk/18.0.1+10/openjdk")` works fine.

I submitted a full log to your support email. 

edit: received a response from support

**Comment by mikehearn** [comment]
Thanks. The fix for this is implemented and will ship in the next update, which should be in a few days or less.
