### ISSUE TITLE
jdeps gets executed when jvm args are manually specified

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#14]
**Describe the bug**
The `app.jvm.modules` are fully specified without `detect`, but the console shows that jdeps scanning failed

**To Reproduce**
fully specify `app.jvm.modules` without `detect`

**Expected behavior**
jdeps does not get executed

**Screenshots**
![image](https://user-images.githubusercontent.com/5491587/182583114-198b140d-001b-49af-a35d-beb1e8ab6e49.png)

**Additional context**

The process doesn't fail, and subsequent calls seem to be cached, so it's a minor thing.

[Internal bug link](https://youtrack.hq.hydraulic.software/issue/CO-206)

**Comment by mikehearn** [comment]
This is fixed by Conveyor 2.1
