### ISSUE TITLE
Setting `app.revision` produces incorrect linux package version

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#24]
**Describe the bug**
Setting `app.revision` breaks the linux package version

```
app.version = 1.0
app.revision = 1
```

![image](https://user-images.githubusercontent.com/5491587/182952683-6999d7fa-cd60-49fc-8ad5-31dc8df2cd8e.png)

**Comment by mikehearn** [comment]
Thanks for the bug report! A fix will be in the next release. There was an overly tight regex which escaped notice; the test suite has been improved to both verify the version number check against various inputs and also use a revision in the integration tests. I'll close this bug once the release is done.
