### ISSUE TITLE
generated macOS installer command does not work

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#25]
**Describe the bug**

The [generated  ](https://ennerf.github.io/HdrHistogramVisualizer/download.html) `curl https://github.com/ennerf/HdrHistogramVisualizer/releases/latest/download/launch.mac | bash` does nothing. 

```
$ curl https://github.com/ennerf/HdrHistogramVisualizer/releases/latest/download/launch.mac | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

Changing it to `wget -qO- https://github.com/ennerf/HdrHistogramVisualizer/releases/latest/download/launch.mac | bash` executes the script, but results in a signature error. The same error occurs when downloading the script through the browser.

```
$ wget -qO- https://github.com/ennerf/HdrHistogramVisualizer/releases/latest/download/launch.mac | bash
Downloading HdrHistogramVisualizer ...

Extracting to /Applications ...
ditto: Couldn't read PKZip signature
```

**Comment by ennerf** [comment]
Might be related to https://stackoverflow.com/a/71879433/3574093

**Comment by mikehearn** [comment]
Seems we never tested hosting the scripts on GH releases. The `curl` command needs the `-L` flag to follow redirects.

Likewise, the script itself uses curl without passing -L. I think we only tested GH releases with signed apps. It should be an easy fix. For example this command works:

`curl -L https://github.com/ennerf/HdrHistogramVisualizer/releases/latest/download/launch.mac | sed 's/curl /curl -L /g'| bash`

@ogpublic Another one for you Ovi, it's [CO-213](https://youtrack.hq.hydraulic.software/issue/CO-213). Should be a very fast fix.
