### ISSUE TITLE
Docs: OS paths to defaults.conf are hard to find (minor)

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#29]
I tried to figure out the paths to the default files on different OS, but the docs section is not easy to find https://conveyor.hydraulic.dev/1.0/configs/hocon-extensions/#per-user-defaults. I eventually got there from the section about backing up keys https://conveyor.hydraulic.dev/1.0/keys-and-certificates/#keys-in-conveyor.

I think it may be good to add another reference to https://conveyor.hydraulic.dev/1.0/running/#initial-setup or https://conveyor.hydraulic.dev/1.0/configs/#writing-config-files or maybe in the OS specific sections https://conveyor.hydraulic.dev/1.0/configs/mac/

Down the line it'd be nice to have a `--show-defaults` command similar to `--show-log`

**Comment by mikehearn** [comment]
The plan is to unbundle the defaults file so you can find it in the install directory (currently it's hidden inside the JARs) but a way to view the defaults in a pager would also be very useful indeed.

**Comment by mikehearn** [comment]
By the way, you can run `conveyor json` to see the full config including resolved defaults. That isn't quite as good as the original defaults file, because it's in json format and is merged with your own, but it lets you see what's there.

**Comment by ennerf** [comment]
My use case was importing existing seed words into the defaults file on a different machine, so I needed to edit it.
