### ISSUE TITLE
Private maven repo in generated compose project

### ISSUE THREAD

**Issue by ionspin** [hydraulic-software/conveyor#32]
**Describe the bug**
A small thing, I noticed settings.gradle.kts contains: 
```
        maven("file:///Users/mike/Hydraulic/product/open/build/repo")
```

**To Reproduce**
Run `./conveyor-2.1/bin/conveyor generate compose --rdns=test`

**Expected behavior**
No local paths are present in settings.gradle.kts

**Comment by mikehearn** [comment]
D'oh! Thanks for letting us know. This will be fixed in the next bugfix release.

**Comment by mikehearn** [comment]
By the way - it's safe to just delete this line. It doesn't have to be changed to anything else.
