### ISSUE TITLE
Behavioral differences between conveyor run and conveyor make app

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#56]
**Describe the bug**
I'm trying to package an FXSampler based app (see [chart-fx#580](https://github.com/fair-acc/chart-fx/pull/580)). `conveyor run` behaves as expected, but `conveyor make windows-app` and running the executable doesn't find the samples (uses reflection).

Can you think of anything that would be different between the `run` and `make app` commands?

**To Reproduce**
1. checkout the branch in [chart-fx#580](https://github.com/fair-acc/chart-fx/pull/580)
2. `clean package -DskipTests --projects chartfx-samples -am` (using JDK 15)
3. `cd chartfx-samples`
4. `conveyor run` (works)
5. `conveyor make windows-app` and double-click the `.exe` (does not work)

**Expected behavior**
Both versions should act the same.

**Screenshots**
| conveyor run | conveyor make windows-app |
|--------------|---------------------------|
| ![image](https://user-images.githubusercontent.com/5491587/230411287-c2fdeee4-4347-4f61-adc0-861aae3f288c.png)| ![image](https://user-images.githubusercontent.com/5491587/230411505-518779b8-0fb8-4b9f-82dd-e9c0cefad3e5.png)|

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mikehearn** [comment]
That's very weird. Off hand I can't think of what could cause that. The run command is extremely simple. It literally just triggers the build of the app task, and then locates the first entry point and runs it.

What's the exception?

Random things to try:

- Use `make app --rerun` to clear the cache? Hard to imagine how it might cause problems.
- How are you running the exe? Is it possible there's a dependency on argv[0] being relative/absolute or something like that?

**Comment by ennerf** [comment]
> How are you running the exe? Is it possible there's a dependency on argv[0] being relative/absolute or something like that?

Good call. That "fixed" it. It seems to execute correctly when it gets run from anywhere other than the bin directory.

The code is just calling into [ControlsFX](https://github.com/controlsfx/controlsfx), so I have a feeling this will be a pain to debug... 😠

```java
import fxsampler.FXSampler;

public class ChartFxSampler {
    public static void main(String[] args) {
        FXSampler.main(args);
    }
}
```

It doesn't look like a Conveyor issue, so I'll go ahead and close it.

**Comment by mikehearn** [comment]
It might still be an issue - maybe when argv[0] isn't a path our custom JNI launcher code isn't doing something that the `java` binary would and that's an appcompat issue. When you find the difference let us know. It could be as simple as a one line fix on our end.

**Comment by ennerf** [comment]
I found nothing 😔

**Comment by mikehearn** [comment]
OK, I'll take a look when I get a chance.  What's the stack trace?

**Comment by ennerf** [comment]
Found the issue.

It's using an older version of FXSampler that searches for jars/directories at or below the working directory: [SampleScanner.java#L173-L197](https://github.com/controlsfx/controlsfx/blob/6b74e0be9b2599e2645c0de234e5eb99123d587d/fxsampler/src/main/java/fxsampler/util/SampleScanner.java#L173-L197).

* `conveyor run` works because the working directory is the project path, so it's finding the jars/classes from the `target` directory
* running from below `bin/..` or from `app/` works because it's in the search path
* running from `bin/` or  `legal/` doesn't work

The latest version unfortunately only loads examples on the module path, so that one doesn't work at all.

**Comment by ennerf** [comment]
Afaik there is no way to change the working directory post VM startup, so besides fixing it upstream (the right thing to do), I can only think of two workarounds:

* add `-Duser.dir=<appDir>` on the VM options
Is there by any chance some template that inserts the correct path when the native wrapper gets executed?

* figure out which executable called it and run it again in another process with an appropriate working dir. 
Is there a simple-ish way to get the name and path of the executable without special casing every platform?

**Comment by mikehearn** [comment]
I'm not sure overriding `user.dir` would work, but you could try this:

```
app.jvm.system-properties.user.dir = &&/../
```

and see if it affects the working directory. `&&` is a special token that means "the place where the exe is found".

Presumably you can't use the existing samples as auto modules?

A couple of alternatives that spring to mind:

1. If there's no console attached, set the default working directory to the root of the app package in the C++ EXE we provide that runs before the JVM starts up.
2. A tool that auto-module-ifies a classpath (i.e. combines jars, computes a module descriptor for them all)

I've been meaning to do (2) for ages but never got around to it. Like, give it a Maven coordinate or some inputs and it'd spit out a "real" module, so like auto-mods but better because they'd have real dependency data and jlink would accept them.

**Comment by ennerf** [comment]
Thanks, the `&&/..` works and is a nicer workaround 👍 

I'm not a primary maintainer on that project, so modularizing it is out of scope. I figured I could quickly add a conveyor configuration, but I completely underestimated the brittleness of the ControlsFX Sampler project.

RE (2) I've run into so many issues with modules that I stopped trying to have fully-modularized projects. Most of the time I'm also shading/shrinking jars, so all of the original module configuration files disappear anyways. It'd be nice to have a tool that reliable takes care of it, but please add a flag to disable it in case something goes wrong.
