### ISSUE TITLE
The Apple notarization service is refusing access

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#65]
Starting today I've been running into errors with the notarization process. I've tried different projects w/ local runners and CI, but `conveyor make site` (mostly v8.0) always produces the error below. The signing certificate hasn't expired yet, so this might be something on the Conveyor end. Do you know whether Apple changed something and/or how to fix it?

```
Error: Task failed: Notarized Mac App for Intel: The Apple notarization service
is refusing access: A required agreement is missing or has expired.
This request requires an in-effect agreement that has not been signed or has
expired.
```

**Comment by mikehearn** [comment]
You may have to log in to the Apple Developer website and accept a changed developer agreement.

**Comment by ennerf** [comment]
That was it 👍
