### ISSUE TITLE
Task Failed: Download Link (linker-idk)

### ISSUE THREAD

**Issue by edko99** [hydraulic-software/conveyor#70]
**Describe the bug**
When running `conveyor make windows-app`, the process stops with the message:
Task failed: Download Link (linker-idk)
- SSL Handshake: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
- Sun Cert Path Builder: unable to find valid certification path to requested target

**To Reproduce**
1. conveyor generate compose com.example.my-project
2. cd my-project
3. ./gradlew jar
4. conveyor make windows-app

**Expected behavior**
A Windows exe file

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1
 

**Additional context**
I check manually in my command line, and I can run jlink without problems

**Comment by mikehearn** [comment]
Hmm that's a new one. It's possible the site hosting the JDK used for jlinking had a temporary SSL messup? Otherwise there may be something odd about your system's certificate store. If you run `conveyor --show-log` do you see anything interesting at the bottom?

**Comment by edko99** [comment]
Yes, it was a certificate issue in my machine. I tried from another machine, and it worked. Thank you.
