### ISSUE TITLE
Mac signing breaks Jetpack Compose / skiko

### ISSUE THREAD

**Issue by gotson** [hydraulic-software/conveyor#75]
**Describe the bug**
I am in the process of integrating Conveyor into my application. So far it worked well, and i could generate a Jetpack Compose application that runs on my Mac M1.

After enabling signing with my Apple Developer certificate, the app breaks on launch:
<img width="255" alt="image" src="https://github.com/hydraulic-software/conveyor/assets/2139133/49dccaca-9c7d-489f-9039-4b2e716a0a08">

If i disable signing, the app works again.

**To Reproduce**

**Expected behavior**
The app should run fine.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5

Here is my `conveyor.conf`:

```
include "#!./gradlew -q :komga-tray:printConveyorConfig"

app {
    display-name = Komga
    fsname = komga
    vcs-url = "https://github.com/gotson/komga"
    description = "Media server for comics/mangas/BDs with API and OPDS support"
    license = MIT
    icons = "res/komga_text_as_path.svg"

    jvm {
        options += "--enable-preview"
        modules = ["java.management", "java.naming", "java.instrument", "java.sql", "jdk.unsupported", "jdk.security.jgss", "java.desktop"]
        mac.options += "-Djava.library.path=<libpath>:/opt/homebrew/lib/:/usr/local/lib/"
        mac.options += "-Dspring.profiles.include=mac"
        windows.options += "-Dspring.profiles.include=windows"
    }

    site {
        base-url = "localhost:3000"
    }
}

conveyor.compatibility-level = 11
```

**Comment by gotson** [comment]
After some investigation i found https://github.com/JetBrains/compose-multiplatform/issues/2895

It seems this is not related to Conveyor, but to Skiko cache. I deleted the skiko cache in `~/.skiko` and it seems to work now.

**Comment by mikehearn** [comment]
Please see:

https://conveyor.hydraulic.dev/10.1/troubleshooting/troubleshooting-jvm/#unsatisfiedlinkerror-mapping-process-and-mapped-file-non-platform-have-different-team-ids

**Comment by gotson** [comment]
> Please see:
> 
> https://conveyor.hydraulic.dev/10.1/troubleshooting/troubleshooting-jvm/#unsatisfiedlinkerror-mapping-process-and-mapped-file-non-platform-have-different-team-ids

Yes, I found that afterwards. Thanks.
