### ISSUE TITLE
Missing docs page for file association warning

### ISSUE THREAD

**Issue by ennerf** [hydraulic-software/conveyor#79]
I get a warning for some custom mac file associations, but the docs link https://conveyor.hydraulic.dev/latest/configs/redir/mac-file-associations returns a 404

## **warning message**
![image](https://github.com/hydraulic-software/conveyor/assets/5491587/ebb2b37e-3701-4cb6-a9a3-5794bb0cb491)

## **404 - not found**
![image](https://github.com/hydraulic-software/conveyor/assets/5491587/0a2d88ba-2779-47c5-b053-a5a56b96f243)

**Comment by mikehearn** [comment]
Sorry about that. We'll get it fixed. The right link is:

https://conveyor.hydraulic.dev/11.1/configs/mac/#file-associations
