### ISSUE TITLE
Broken download link for eton-sample

### ISSUE THREAD

**Issue by mipastgt** [hydraulic-software/conveyor#83]
The download link https://downloads.hydraulic.dev/eton-sample/download.html to the sample app in the README.md of the https://github.com/hydraulic-software/eton-desktop repo is broken. (The requested URL was not found on this server.)

**Comment by mikehearn** [comment]
Whoops, thank you! It's fixed now. We should update the link checker to cover the sample app READMEs as well.

The fixed URL is: https://hydraulic-software.github.io/eton-desktop/download.html
