### ISSUE TITLE
Custom builds 

### ISSUE THREAD

**Issue by Christilut** [hydraulic-software/conveyor#92]
I talked about this on Discord a while back but thought I'd make a feature request so we can track it.

**Is your feature request related to a problem? Please describe.**
I have a software program that I build and release with Conveyor, it's great. But quite often users run into a very specific bug that only affects them at that moment.
This is what I normally do (before conveyor):
1. I create a fixed version (same version number) and send it over to the user. 
2. They install with the fix and they are happy. 
3. Because it's the same version number, whenever a real update comes out (that has all the fixes including the one I made for them), they are updated and they're back on the normal releases.

The problem is that I can't really recreate that workflow with Conveyor. When I make a custom build and send it to the user, they will run the EXE or launch the APP file, the auto updater kicks in and downloads the official build from the download site.

**Describe the solution you'd like**
What I would like is a way to send custom builds to my users:
1. They can install it offline, from the file I sent them
2. It has the same version number as the current official build
3. Once a new official version is released, they are auto updated as normal

**Describe alternatives you've considered**
What would work is just increasing the version number by one patch for each custom build. No new version is downloaded until the version number on the download site is higher. But that's really ugly since the versioning gets holes in it for every experimental build.

Another thing that kind of works is to not send the EXE to the user but the MSI installer. They will need to uninstall the program first or Windows won't allow a reinstall. But when the user quits the program and launches it the normal way, the auto updater kicks in.

A custom build download site is another possible solution I looked at but then the auto updater has no way to know when an official build is released.

**Possible solutions and ideas**
Would a 4th version number part work? E.g. `1.0.0.1` Not sure if that is semver and I've seen tools break on that in the past, but if conveyor understands it then that could work.

A different approach could be a magic string in the filename. Like `[CUSTOM BUILD]` or maybe even an option so we can choose what the magic string will be. If that string is detected in the filename, the updater would install from the disk (so it won't download from the download site) and it would not update until a new version is found.

**Comment by mikehearn** [comment]
The `app.revision` key is meant for this use case, it sets the last number in the version quad. However, the download page and other user visible places won't show it, so you can use this to increment the version in a way that's less visible.

One way we've thought about to do this is to let the update site URL be different to the upload URL, but this would still require you to leave holes in your versions. We're OK with that for Conveyor because we only use two version segments anyway. Is it really the case that 4 aren't enough?

**Comment by Christilut** [comment]
I'm only using 3 numbers in my version so app.revision sounds like a good solution. I'll give that a try and see how it goes 👍
