### ISSUE TITLE
Enable draft release for github

### ISSUE THREAD

**Issue by Abisco** [hydraulic-software/conveyor#93]
**Is your feature request related to a problem? Please describe.**
Our teams approach for electron-forge used to be to make a draft release for our production environment, then have our qa team test it before marking it as the latest release, it would be nice for hydraulic to have this

**Describe the solution you'd like**
A github conveyor config variable for draft release

**Describe alternatives you've considered**
Right now i think what we're doing is going in to the release and changing it to pre-release, but this is a manual process that adds overhead to the teams process

**Comment by mikehearn** [comment]
Good suggestion, thanks. Have you verified that a draft release isn't pointed to by /releases/latest ? I couldn't immediately see in the docs whether that URL includes draft releases, although presumably it doesn't.

**Comment by Abisco** [comment]
I'm pretty confident that draft releases are not pointed to by /releases/latest, I believe it takes the last/latest non draft since drafts are only visible to the admins of the repo.

Here's what I could find from github on it:
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release

> View the latest published full release for the repository.
> The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute.

**Comment by mikehearn** [comment]
Thanks!

**Comment by mikehearn** [comment]
This will go out in the next major release.

**Comment by mikehearn** [comment]
This has shipped.
