### ISSUE TITLE
"Try installing an app that uses it" goes to -> Not found

### ISSUE THREAD

**Issue by iSuslov** [hydraulic-software/conveyor#94]
<img width="1230" alt="Screenshot 2024-01-21 at 9 40 43 PM" src="https://github.com/hydraulic-software/conveyor/assets/7628774/0aa511ce-5b20-4797-9ccc-ec6c727700f1">

**Comment by mikehearn** [comment]
Whoops, the repo README isn't checked by the 404 checker. Thanks for the report.
